### ISSUE TITLE
We still need a localization platform

### ISSUE THREAD

**Issue by NotFenixio** [meower-media-co/i18n#7]
Self-explanatory.

So, I've been researching for a bit and all online, "free" platforms are trash.

The very last option is to self-host.

Some options are Pontoon, Weblate, etc.

Any idea for the platform/host?

**Comment by mdwalters** [comment]
or we could make our own, call it, meowytranslate

**Comment by mdwalters** [comment]
[we have a weblate project now!](https://hosted.weblate.org/projects/meower/)
